name: example
dependencies:
  built_collection: ^5.1.1
  built_value: ^8.4.3
  hive: any
dev_dependencies:
  build_runner: any
  built_value_generator: ^8.4.3
  hive_generator:
    path: ..
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependency_overrides:
  hive:
    path: ../../hive
  hive_generator:
    path: ..